# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7adacd4ecccc611178b8d320e2dd320e15099d0521f84430d7c780df04c12c18ecae976d4a1ca24cde7404ce434f7a25016ad9ecf8c411035ccb9f1b876764b1

test:
  secret_key_base: 645ae1a29c5ebced1263fec558a1de34167296952ab0cb99f57c563e095cb832207e9fc69a0c04a7a4fb298a0d1c5c390c4876b658d30e3e174def2795007208

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
